import { scaleSpacing } from 'utils';

const spacing = {
  sH: scaleSpacing(8, 'horizontal'),
  sV: scaleSpacing(8, 'vertical'),
  mH: scaleSpacing(16, 'horizontal'),
  mV: scaleSpacing(16, 'vertical'),
  lH: scaleSpacing(24, 'horizontal'),
  lV: scaleSpacing(24, 'vertical'),
  xlH: scaleSpacing(32, 'horizontal'),
  xlV: scaleSpacing(32, 'vertical'),
  '2xlH': scaleSpacing(40, 'horizontal'),
  '2xlV': scaleSpacing(40, 'vertical'),
  '3xlH': scaleSpacing(48, 'horizontal'),
  '3xlV': scaleSpacing(48, 'vertical'),
  '4xlH': scaleSpacing(56, 'horizontal'),
  '4xlV': scaleSpacing(56, 'vertical'),
  '5xlH': scaleSpacing(64, 'horizontal'),
  '5xlV': scaleSpacing(64, 'vertical'),
  '6xlH': scaleSpacing(72, 'horizontal'),
  '6xlV': scaleSpacing(72, 'vertical'),
  '7xlH': scaleSpacing(80, 'horizontal'),
  '7xlV': scaleSpacing(80, 'vertical'),
  '8xlH': scaleSpacing(88, 'horizontal'),
  '8xlV': scaleSpacing(88, 'vertical'),
  '9xlH': scaleSpacing(96, 'horizontal'),
  '9xlV': scaleSpacing(96, 'vertical'),
  '10xlH': scaleSpacing(104, 'horizontal'),
  '10xlV': scaleSpacing(104, 'vertical'),
  '11xlH': scaleSpacing(112, 'horizontal'),
  '11xlV': scaleSpacing(112, 'vertical'),
  '12xlH': scaleSpacing(120, 'horizontal'),
  '12xlV': scaleSpacing(120, 'vertical'),
};

export default spacing;
